// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMo6aXi2Ge3cvgS9QUKU6-hoGqnbkxH60',
    appId: '1:331922913075:android:2bf38b07f6998a4073f046',
    messagingSenderId: '331922913075',
    projectId: 'expense-app-1d0ca',
    storageBucket: 'expense-app-1d0ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7gFuy2vuv1ow0I_HBSmDCPjPD4KtE3VA',
    appId: '1:331922913075:ios:c50e1854c35f157873f046',
    messagingSenderId: '331922913075',
    projectId: 'expense-app-1d0ca',
    storageBucket: 'expense-app-1d0ca.firebasestorage.app',
    iosClientId:
        '331922913075-rqjjb0t6tnsioen6flqtshmgmvhtcfuq.apps.googleusercontent.com',
    iosBundleId: 'com.dailyfinance.dailyFinanceTracker',
  );
}
